### ISSUE TITLE
telescope.py の display_focal_plane 関数で ax が NoneType になりエラーが出る

### ISSUE THREAD

**Issue by tkamizuka** [xr0038/jasmine_warpfield#2]
astrometry-challenge の generate_case3.py を実行したところ、下記のエラーを得ました。

```
Traceback (most recent call last):
  File "generate_case3.py", line 82, in <module>
    generate_challenge(filename)
  File "generate_case3.py", line 45, in generate_challenge
    jasmine.display_focal_plane(sources)
  File "/home/kamizuka/.pyenv/versions/anaconda3-2018.12/lib/python3.7/site-packages/warpfield/telescope.py", line 293, in display_focal_plane
    ax.set_aspect(1.0)
AttributeError: 'NoneType' object has no attribute 'set_aspect'
```

telescope.py の display_focal_plane 関数の中の ax が NoneType になっているようです。
ax は fig.add_subplot で生成していますが、この引数を空にした場合にこうなるようです。
111 を引数にしたりすると問題なく動作するようでした。
ご確認いただけますと幸いです。

ちなみに上塚の環境ですが、
python のバージョンは 3.7.1 (pyenv の anaconda3-2018.12)、
matplotlib のバージョンは 3.0.2 となっております。

**Comment by xr0038** [comment]
開発環境は 3.3.4 でした．

``` bash
$ pip freeze | grep matplotlib
matplotlib==3.3.4
```

以下を見ると 3.1.0 から引数なしが `add_subplot(111)` にエイリアスされるようになったようです．
https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.1.0.html#figure-add-subplot-with-no-arguments

`setup.py` には `matplotlib>=3.0.0` と書いてしまったので問題になっていたようです．とりいそぎ requirements を修正 & `add_subplot` の引数を省略していたところに `111` を追加しようと思います．

**Comment by tkamizuka** [comment]
了解しました。何卒よろしくお願いいたします。
